# Generated by Django 5.1 on 2024-08-11 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("source", models.CharField(max_length=50)),
                ("price_usd", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "market_cap_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=30, null=True
                    ),
                ),
                (
                    "volume_24h_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=30, null=True
                    ),
                ),
                (
                    "percent_change_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "indexes": [
                    models.Index(
                        fields=["symbol"], name="portfolios__symbol_2ce9d2_idx"
                    ),
                    models.Index(
                        fields=["source"], name="portfolios__source_1682bb_idx"
                    ),
                    models.Index(
                        fields=["last_updated"], name="portfolios__last_up_027def_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PortfolioHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=10, default=0, max_digits=20),
                ),
                ("date_acquired", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "cost_basis",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=30, null=True
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolios.asset",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Holding",
                "verbose_name_plural": "Portfolio Holdings",
                "indexes": [
                    models.Index(
                        fields=["portfolio", "asset"],
                        name="portfolios__portfol_0c572b_idx",
                    )
                ],
                "unique_together": {("portfolio", "asset")},
            },
        ),
    ]
