# Generated by Django 5.1 on 2024-08-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
        ('portfolios', '0002_alter_portfolioholding_asset_delete_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('transaction_date', models.DateField()),
                ('price_at_transaction', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fees', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Transaction',
                'verbose_name_plural': 'Portfolio Transactions',
                'indexes': [models.Index(fields=['portfolio', 'asset', 'transaction_date'], name='portfolios__portfol_701b07_idx')],
            },
        ),
    ]
