# Generated by Django 5.1 on 2024-08-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0003_portfoliotransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliotransaction",
            name="transaction_date",
            field=models.DateTimeField(),
        ),
    ]
