# Generated by Django 5.1 on 2024-08-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0004_alter_portfoliotransaction_transaction_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PortfolioHolding",
        ),
    ]
