services:
  web:
    build: . # crea imagen usando el Dockerfile en este directorio
    container_name: django-api
    image: crypto-portfolio-manager:latest
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000" # Deberia configurar Gunicorn
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
    - POSTGRES_USER=hello_django
    - POSTGRES_PASSWORD=hello_django
    - POSTGRES_DB=hello_django_prod
    volumes:
      - postgres_data:/var/lib/postgres/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: