services:
  web:
    image: hernansaa/crypto-portfolio-manager:${IMAGE_TAG}
    container_name: crypto-portfolio-manager
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        # gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3
        NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    ports:
      - "8000"
    env_file:
      - .env.prod
    volumes:
      - static:/static
      - django_logs:/logs
    restart: always
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgres/data/
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - nginx_logs:/var/log/nginx
    ports:
      - "8000:80"
    depends_on:
      - web
    restart: always

  newrelic:
    build: ./newrelic
    environment:
      NEW_RELIC_APP_NAME="crypto-portfolio-manager"
      NEW_RELIC_LICENSE_KEY=eu01xx331477306f612f5bdabacbd120FFFFNRAL
    depends_on:
      - web
    restart: always

volumes:
  static:
  postgres_data:
  django_logs:
  nginx_logs: