# Generated by Django 5.1 on 2024-08-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("source", models.CharField(max_length=50)),
                ("price_usd", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "market_cap_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=30, null=True
                    ),
                ),
                (
                    "volume_24h_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=30, null=True
                    ),
                ),
                (
                    "percent_change_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "indexes": [
                    models.Index(
                        fields=["symbol"], name="market_data_symbol_514549_idx"
                    ),
                    models.Index(
                        fields=["source"], name="market_data_source_56651d_idx"
                    ),
                    models.Index(
                        fields=["last_updated"], name="market_data_last_up_5f4bc3_idx"
                    ),
                ],
            },
        ),
    ]
